name: VS17-CI

on: [push, pull_request]

jobs:
  ci:
    name: vs17/${{matrix.arch}}/${{matrix.cfg}}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {gen: Visual Studio 17 2022, arch: x64, cfg: Release}
          - {gen: Visual Studio 17 2022, arch: x64, cfg: Debug}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: configure
        run: |
          cmake -S . -B build -G "${{matrix.gen}}" -A ${{matrix.arch}} 
      - name: build
        run: |
          cmake --build build --verbose --config ${{matrix.cfg}} --parallel
      - name: test
        run: |
          cd build &&
          ctest --output-on-failure -C ${{matrix.cfg}}
